version: "3"
services:
  #PHP Service
  app:
    image: larux/:latest
    container_name: "..._PHP"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - boss-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "..._NGINX"
    restart: unless-stopped
    tty: true
    ports:
      - "...:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - boss-network

#Docker Networks
networks:
  boss-network:
    driver: bridge
